[versions]
agp = "8.8.0"
androix-core-ktx = "1.15.0"
androix-navigation-ui-ktx = "2.8.6"
androix-navigation-fragment-ktx = "2.8.6"
androix-lifecycle-viewmodel-ktx = "2.8.7"

kotlin = "2.1.10"
kotlinx-serialization-json = "1.8.0"
hidden-api = "4.3.3"
material = "1.12.0"
swiperefreshlayout = "1.2.0-alpha01"
modernandroidpreferences = "2.3.2"

[libraries]
material = { module = "com.google.android.material:material", version.ref = "material" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "androix-core-ktx" }
modernandroidpreferences = { module = "de.maxr1998:modernandroidpreferences", version.ref = "modernandroidpreferences" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androix-navigation-ui-ktx" }
navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androix-navigation-fragment-ktx" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androix-lifecycle-viewmodel-ktx" }
swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }

xposed = { module = "de.robv.android.xposed:api", version = "82" }
ezXHelper = { module = "com.github.kyuubiran:EzXHelper", version = "2.2.0" }
dev-rikka-hidden-compat = { module = "dev.rikka.hidden:compat", version.ref = "hidden-api" }
dev-rikka-hidden-stub = { module = "dev.rikka.hidden:stub", version.ref = "hidden-api" }
dexkit = { module = "org.luckypray:dexkit", version = "2.0.3" }
lyricGetter-api = { module = "com.github.xiaowine:Lyric-Getter-Api", version = "6.0.0" }
xkt = { module = "com.github.xiaowine:XKT", version = "1.0.12" }
dsp = { module = "com.github.xiaowine:dsp", version = "1.1.3" }
cardSlider = { module = "com.github.IslamKhSh:CardSlider", version = "1.0.1" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
refine = { id = "dev.rikka.tools.refine", version = "4.4.0" }
